<?php

return [

    'contact' => [
        'title' => 'Contact Us',
        'subtitle' => 'Get in touch with us today!',
        'description' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'bg_color' => '#fff',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
    'about' => [
        'title' => 'About Us',
        'subtitle' => 'Learn more about our company',
        'description' => 'We are a team of dedicated professionals who are passionate about what we do. Learn more about our history, values, and mission.',
        'bg_color' => '#fafafa',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
   'privacy' => [
        'name' => 'Privacy Policy',
        'title' => 'Privacy Policy',
        'subtitle' => 'Protecting your privacy is important to us',
        'description' => 'Read about our privacy practices and how we protect your personal information.',
        'bg_color' => '#fff',
        'image' => 'privacy.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'privacy',
        'details' => 'Read about our privacy practices and how we protect your personal information.',
        'meta_title' => 'Privacy Policy',
        'meta_description' => 'Protecting your privacy is important to us',
        'link' => '/privacy',
    ],

    'products' => [
        'title' => 'Products',
        'subtitle' => 'Shop our wide selection of products',
        'description' => 'Browse our selection of products and find the perfect item for you.',
        'bg_color' => '#fff',
        'image' => 'products.jpg',
        'featured_title' => 'Shop our products',
        'label' => 'some',
        'position' => '1',
        'slug' => 'products',
        'details' => 'Browse our selection of products and find the perfect item for you.',
        'meta_title' => 'Products',
        'meta_description' => 'Shop our wide selection of products',
        'link' => '/products',
    ],
    'shipping' => [
        'title' => 'Shipping',
        'subtitle' => 'Learn about our shipping rates and policies',
        'description' => 'We offer free shipping on orders over $50. For orders under $50, shipping costs vary depending on the destination. We also offer a variety of shipping methods, including standard shipping, expedited shipping, and overnight shipping.',
        'bg_color' => '#fff',
        'image' => 'shipping.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'shipping',
        'details' => 'We offer free shipping on orders over $50. For orders under $50, shipping costs vary depending on the destination. We also offer a variety of shipping methods, including standard shipping, expedited shipping, and overnight shipping.',
        'meta_title' => 'Shipping',
        'meta_description' => 'Learn about our shipping rates and policies',
        'link' => '/shipping',
    ],
    'blog' => [
        'title' => 'Blog',
        'subtitle' => 'Stay up-to-date on the latest news and trends',
        'description' => 'Our blog is a great place to stay up-to-date on the latest news and trends in ourindustry. We post regularly about new products, industry news, and helpful tips.',
        'bg_color' => '#fff',
        'image' => 'blog.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'blog',
        'details' => 'Our blog is a great place to stay up-to-date on the latest news and trends in our industry. We post regularly about new products, industry news, and helpful tips.',
        'meta_title' => 'Blog',
        'meta_description' => 'Stay up-to-date on the latest news and trends in our industry',
        'link' => '/blog',
    ],
    'terms' => [
        'name' => 'Terms and Conditions',
        'title' => 'Terms and Conditions',
        'subtitle' => 'Please read our terms and conditions carefully before using our website',
        'description' => 'By using our website, you agree to be bound by our terms and conditions. Please read them carefully before using our website.',
        'bg_color' => '#fff',
        'image' => 'terms.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'terms',
        'details' => 'By using our website, you agree to be bound by our terms and conditions. Please read them carefully before using our website.',
        'meta_title' => 'Terms and Conditions',
        'meta_description' => 'Please read our terms and conditions carefully before using our website',
        'link' => '/terms',
    ],
    'faq' => [
        'name' => 'FAQ',
        'title' => 'FAQ',
        'subtitle' => 'Frequently asked questions',
        'description' => 'Frequently asked questions about our products and services.',
        'bg_color' => '#fff',
        'image' => 'faq.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'faq',
        'details' => 'Frequently asked questions about our products and services.',
        'meta_title' => 'FAQ',
        'meta_description' => 'Frequently asked questions about our products and services.',
        'link' => '/faq',
    ],
            
];
